import { Download } from 'lucide-react'
import { useApp } from '../../context/AppState'
import { RISK_ZONES } from '../../data/mockData'

export default function Reports() {
  const { activeIncident, alerts, actions, horizon, warningsIssued, predictionMeta, conditions } = useApp()
  const meta = predictionMeta[horizon]

  const exportReport = () => {
    const lines = [
      `NAFT-GUARD — INCIDENT REPORT`,
      `Generated by Team TechLADS`,
      ``,
      `Incident: ${activeIncident.id}`,
      `Detected: ${activeIncident.detectedAt}`,
      `Location: ${activeIncident.location}`,
      `Estimated area: ${activeIncident.area} km²`,
      `Detection confidence: ${activeIncident.confidence}%`,
      `Severity: ${activeIncident.severity}`,
      `Status: ${activeIncident.status}`,
      ``,
      `PREDICTED SPREAD (${horizon})`,
      `Direction: ${meta.direction}`,
      `Velocity: ${meta.velocity}`,
      `Coastal arrival: ${meta.arrival}`,
      `Confidence: ${meta.confidence != null ? `${meta.confidence}%` : `${activeIncident.confidence}% (detection)`}`,
      `Wind: ${conditions.windDirection} at ${conditions.windSpeed}`,
      `Current: ${conditions.current}`,
      ``,
      `ENVIRONMENTAL IMPACT`,
      ...RISK_ZONES.map((r) => `- ${r.name}: ${r.level}`),
      ``,
      `WARNING HISTORY`,
      `Warnings issued to date: ${warningsIssued}`,
      ...alerts.map((a) => `- ${a.time} — ${a.text}`),
      ``,
      `RESPONSE ACTIONS`,
      ...actions.map((a) => `- [${a.status}] ${a.title} (${a.priority})`),
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `naft-guard-report-${activeIncident.id}.txt`
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <section className="panel report-panel">
      <div className="panel-head">
        <div>
          <span className="eyebrow">Case Report</span>
          <h2>Incident Summary — {activeIncident.id}</h2>
        </div>
        <button className="btn-primary" onClick={exportReport}>
          <Download size={15} /> Export Report
        </button>
      </div>

      <div className="report-grid">
        <div className="report-card">
          <h4>Incident Summary</h4>
          <div className="kv-grid">
            <div><label>Location</label><strong>{activeIncident.location}</strong></div>
            <div><label>Spill area</label><strong>{activeIncident.area} km²</strong></div>
            <div><label>Detection confidence</label><strong>{activeIncident.confidence}%</strong></div>
            <div><label>Status</label><strong>{activeIncident.status}</strong></div>
          </div>
        </div>

        <div className="report-card">
          <h4>Predicted Spread</h4>
          <div className="kv-grid">
            <div><label>Horizon</label><strong>{horizon}</strong></div>
            <div><label>Direction</label><strong>{meta.direction}</strong></div>
            <div><label>Coastal arrival</label><strong>{meta.arrival}</strong></div>
            <div><label>Drift velocity</label><strong>{meta.velocity}</strong></div>
          </div>
        </div>

        <div className="report-card">
          <h4>Environmental Impact</h4>
          <ul className="mini-list">
            {RISK_ZONES.map((r) => (
              <li key={r.id}><span>{r.name}</span><span className={`sev-tag sev-${r.level.toLowerCase()}`}>{r.level}</span></li>
            ))}
          </ul>
        </div>

        <div className="report-card">
          <h4>Warning History</h4>
          <ul className="mini-list">
            {alerts.slice(0, 5).map((a) => (
              <li key={a.id}><span>{a.time}</span><span>{a.text}</span></li>
            ))}
          </ul>
        </div>

        <div className="report-card span-2">
          <h4>Response Actions</h4>
          <ul className="mini-list">
            {actions.map((a) => (
              <li key={a.id}><span>{a.title}</span><span className="mono-tag">{a.status.replace('_', ' ')}</span></li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  )
}
